# Generated by Django 5.0.1 on 2025-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_email_alter_user_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
