# Generated by Django 5.0.1 on 2025-03-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='session_key',
        ),
    ]
