# Generated by Django 5.0.1 on 2025-03-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_deliverymethod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryMethod',
            new_name='Delivery',
        ),
    ]
