# Generated by Django 5.0.1 on 2025-03-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_deliverymethod_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_method',
            new_name='method',
        ),
    ]
