# Generated by Django 5.0.1 on 2025-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('exist', 'exist'), ('pending', 'pending')], default='exist', max_length=100),
        ),
    ]
