# Generated by Django 5.0.1 on 2025-04-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_cartitem_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
