# Generated by Django 5.0.1 on 2025-04-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.cart'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
