# Generated by Django 5.0.1 on 2025-04-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'session_key')},
        ),
    ]
