# Generated by Django 5.0.1 on 2025-04-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='owned',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
