# Generated by Django 5.0.1 on 2025-04-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_cartitem_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
