# Generated by Django 5.0.1 on 2025-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
