# Generated by Django 5.0.1 on 2025-04-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار پرداخت'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='draft', max_length=20),
        ),
    ]
