# Generated by Django 5.0.1 on 2025-04-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_cart_created_at_alter_cartitem_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at_str',
            field=models.CharField(default=1, editable=False, max_length=18),
            preserve_default=False,
        ),
    ]
