# Generated by Django 5.0.1 on 2025-04-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at_str',
            field=models.CharField(default=1, editable=False, max_length=18),
            preserve_default=False,
        ),
    ]
