# Generated by Django 5.0.1 on 2025-04-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_cart_created_at_str'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
    ]
