# Generated by Django 5.0.1 on 2025-04-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_order_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookStatus',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at_str',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
